### ISSUE TITLE
Mobile driving licence, display vs. present

### ISSUE THREAD

**Issue by joelposti** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#131]
From section 3.2 of the ARF:

> A significant use case for the EUDI Wallet involves allowing Users to acquire, store, and display a mobile Driving Licence (mDL) as an attestation to prove their driving privileges.

What is meant with ‘display’ here? Display to me means that the User visually shows the information of the mobile driving licence to the Relying Party who then visually inspects said information. How would cryptographic validation happen in such case?

If visual inspection is not a use case that needs to be supported, should the verb ‘present’ be used instead which is more commonly used in the ARF?

As a side note I think it would be a good idea to define the meanings of ‘present’, ‘sharing’ and ‘release’ in chapter 2 Definitions.

**Comment by skounis** [comment]
Resolved in https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/commit/b051d313a009c7a60e6fb83d4f2fdf49086f50ac
