### ISSUE TITLE
Difficult to parse sentence in section 7.5.5 of the ARF

### ISSUE THREAD

**Issue by joelposti** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#150]
Section 7.5.5 of the ARF has the following sentence:

> If Relying Party authentication fails for any reason, the Wallet Instance SHALL NOT release the requested attributes to the Relying Party when failures listed below occur.

It is difficult to understand what are the cases when the Wallet Instance shall not release the request attributes.

I think the sentence should be either 

> If Relying Party authentication fails for any reason, the Wallet Instance SHALL NOT release the requested attributes to the Relying Party.

or

> If Relying Party authentication fails for a reason listed below, the Wallet Instance SHALL NOT release the requested attributes to the Relying Party.

**Comment by pinamiranda** [comment]
Thank you for your submission.
The requirement will be reworded in ARF 1.4.0

**Comment by joelposti** [comment]
Looks like the requirement has been reworded and moved to ARF 1.4 Annex 2 RPA_05. This issue can be closed.
