### ISSUE TITLE
Duplicate sentence (typo)

### ISSUE THREAD

**Issue by id-henkmarsman** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#196]
### Description
the following section in the ARF v1.4 has a duplicate sentence in it.

Wallet Instance (WI): The app or application installed on a User device, which is part of an EUDI Wallet Solution and belongs to and is controlled by a User. This component implements the core business logic and interfaces depicted in figure 2. This component implements the core business logic and interfaces as depicted in figure 2. It directly interacts with the WSCA/WSCD to securely manage cryptographic assets and execute cryptographic functions, ensuring a high level of assurance for authentication.

### User Story
Remove the duplicate sentence to have the correct text in the ARF.

### Acceptance Criteria
Duplicate sentence is removed.

### Priority
Low. No harm done at the moment, typo does not introduce errors, is merely a duplicate.

### Estimates
takes 2 minutes

### Technical Notes and Constraints
none

### Dependencies
non

**Comment by digeorgi** [comment]
Thank you very much for your input and contributions. 
The identified issue will be addressed in the service release v1.4.1.
