### ISSUE TITLE
Roll back copy after merge

### ISSUE THREAD

**Issue by skounis** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#228]
The PR https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/187 brings changes we approve except one. After we merge it we should take care of the following fix:

* https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/187#pullrequestreview-2142697305
* https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/187/files#diff-42bd4374f09a239a1feca1e6f45b7aa69e7a59b96d7cbc327414d1109ba59b3fL1221

cc @digeorgi

**Comment by toonn** [comment]
As an explanation of my reasoning and to point out "that" can't be brought back without also removing the preceding comma.

The sentence at hand would become:

> \[Topic 25\] and \[Topic 26\] (combined into one topic), present the current and foreseen status of the catalogues, their creation, distribution, discovery, management and maintenance, that will allow simple update procedures, ...

That is used to introduce a restrictive clause "will allow simple update procedures," and should therefore not be preceded by a comma. However, without the comma it is not clear what that ranges over and it seems to apply only to maintenance, "and (maintenance that will allow simple update procedures)."

My reading of the meaning is that everything summed up is what will allow for the simple update procedures, hence "their property 1, property 2 and property 3, will allow simple update procedures," though it is possible that the comma should still be removed.
