### ISSUE TITLE
Passkeys

### ISSUE THREAD

**Issue by ryanbnl** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#26]
In an earlier draft passkeys was considered one of the key technologies. References appear to have been removed.

What is the reasoning behind this change? The technology has very high potential wrt privacy and security.

In general it would be nice to see the considerations made be included as an appendix to the ARF as that provides more context for the community and ensures that this process becomes (and remains) transparant.

**Comment by madisehastu** [comment]
Dear ryanbnl, 

Thank you for your feedback on our digital identity wallet specification. We appreciate your interest in our project and your valuable input. 

Regarding your question about passkeys, we have currently focused on identifying the user with PID and are still in the process of evaluating implementation options for pseudonymous identification. However, we want to assure you that we recognize the high potential of this technology in terms of privacy and security, and we plan to consider it as a wallet use case in a future version of the document. 

We also appreciate your suggestion to include considerations as an appendix to the ARF. We have plans to develop architecture decision records for the specifications, which will provide more context and transparency to the community. 

Thank you again for your contribution to our project. 

Best regards, 

European Digital Identity Framework Team
