### ISSUE TITLE
[Feature request] Default to UML sequence diagram to document detailed processes

### ISSUE THREAD

**Issue by earizon** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#27]
* Sequence diagrams offer a simple view of processes with actors and messages ordered in time.

* Many free online/desktop tools exists ( [ex1](https://sequencediagram.org/), [ex2](https://plantuml.com/), ...). 

* The syntax is standardized and quick to learn (we can be experts after 30 minutes of playing with it). Some well known development environments allows to render them when embedded as source code.

* They are not as powerful as BMPN diagrams but "good enough" for 95% of tasks and much more "git friendly".

* Seq. Diagrams many times serve as pseudo-code for software real implementations.

My two cents!

**Comment by madisehastu** [comment]
Dear earizon, 

Thank you for your feedback on our digital identity wallet specification. We appreciate your interest in our project and your suggestion to default to UML sequence diagrams to document detailed processes. 

We understand the benefits of using UML sequence diagrams to document processes and will take your suggestion into consideration as we continue to develop and improve the specification. At this time, we are focusing on providing a high-level overview of the digital identity wallet and its features. However, we will consider the use of UML diagrams as more detailed processes are described in the document. 

Thank you again for your contribution to our project. 

Best regards,  

European Digital Identity Framework Team
