### ISSUE TITLE
Support for organisational wallet missing

### ISSUE THREAD

**Issue by lalc** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#30]
This is more of a question than a user story. Currently, the ARF doesn't address Organisational wallet. 

- [ ] Do we contribute to ARF with org wallet content or start a separate document? 
- [ ] Which forum decides such questions?

**Comment by lalc** [comment]
The primary use of organisational wallet based on the pilot we have done in Sweden are:
1) Hold and share organisational data. E.g. business credentials (e.g. legal ID, Board info, tax data, Ecolabels, etc.)
2) Be available for multiple users to control it
3) Procurement usecases
4) Organisational tax management 

This is agreed to be part of the EWC LSPs.

**Comment by lalc** [comment]
> Hi @lalc, Thanks for the question. To be able to answer, can your further explain how you understand "Organisational wallet"? For instance, a wallet that several people can use or a wallet that is able to identify the person controlling it, the identity of the organisation the person is representing and the scope of the representation mandate?

The primary use of organisational wallet based on the pilot we have done in Sweden are:

- Hold and share organisational data. E.g. business credentials (e.g. legal ID, Board info, tax data, Ecolabels, etc.)
- Be available for multiple users to control it
- Procurement usecases
- Organisational tax management

Some of these are agreed to be part of the EUs EWC LSPs as well.

**Comment by madisehastu** [comment]
Hi @lalc,
Thanks for the clarification. Work on the topics you list is not planned as of now for purposes of ARF. We can see several ways to approach the use cases, e.g. through Member State issued legal person PID or through credentials issued as (Q)EAA-s. We note the topic is important for you and will keep it mind for ARF backlog refinement. Of course we look forward to learn from the EWC piloting experience.
