### ISSUE TITLE
PID attribute data model

### ISSUE THREAD

**Issue by spheroid** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#33]
I'm sorry if this isn't the correct venue or I'm getting ahead of myself, but I'd like to know what the current status of the PID attribute data model is?

The PID attributes in question are listed under section 5.1.1.1, but like many things in the current version of the ARF, they are described at a high level. But I've also noticed that Google identity-credential library already has the EU PID mdoc defined (added in PR google/identity-credential#164). Is this something they've just come up with on their own or are there any official drafts of the SD-JWT/VCDM or mdoc presentations available somewhere?

**Comment by madisehastu** [comment]
Hi @spheroid,
Both PID Verifiable Credentials and mdoc schemas are at discussion paper stage currently in the eIDAS Expert Group. There are no official drafts yet. 
Developing the schemas for PID and for mobile Driving Licences are currently planned for April and May.
