### ISSUE TITLE
Clean up the markup for Tables 5 and 6

### ISSUE THREAD

**Issue by skounis** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#38]
### Description
The conversion from `.docx` to `.md` brought unnecessary `blockquote` markup.

![image](https://user-images.githubusercontent.com/690575/230345102-e5432d32-2481-484b-85c6-585f801d5aa2.png)

Examples: 
* https://github.com/eu-digital-identity-wallet/architecture-and-reference-framework/blob/main/arf.md?plain=1#L1089

### Tasks
1. [ ] Remove the `blockquote` elements and clear the markup.

**Comment by skounis** [comment]
We removed the `blockquote` elements  in `v1.2.0`

https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/compare/v1.1.0...v1.2.0

**Comment by pinamiranda** [comment]
Thank you for your input. We've noted your suggestion, and it will be considered for inclusion in the next ARF version (ARF v.1.4).

**Comment by skounis** [comment]
@pinamiranda The changes are already part of `v1.2` 
* https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/compare/v1.1.0...v1.2.0
