### ISSUE TITLE
Incorporate changes regarding Trust Modes, PID and mDL Rule book - ARF v1.2

### ISSUE THREAD

**Issue by skounis** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#67]
### Description
Incorporate the ARF text additions as per 
* https://github.com/eu-digital-identity-wallet/ec-internal-desk/issues/20

### Tasks 
1. [x] Update the copy (markdown) 
2. [ ] Mark new version `v1.2.0`

### Acceptance Criteria
The markdown document reflects the `v1.2.0` draft Word document 

### Acceptance Criteria
The following scenarios shall be covered.

### Resources
* [ARF v1.2.0 working draft](https://eceuropaeu.sharepoint.com/:w:/r/teams/GRP-GRP-CNECTR3-eID/Shared%20Documents/General/ARF/Issue%20%2367%20-%20v1.2.0/1.1%20and%201.2%20compared.docx?d=w712bf30b6a7d4d788cfd3ef3104100c1&csf=1&web=1&e=KRaZVp) (with track changes)

**Comment by CeriseGoutPelican** [comment]
Hello everyone!
Thanks for all your hard work. Do you have any news about releasing v1.2.0 as it was approved at the Expert Group meeting last June?
