### ISSUE TITLE
GitHub Pages not configured properly

### ISSUE THREAD

**Issue by villesundell** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#79]
Hello! :wave: 
It seems that, despite the github-pages deployment is successful (https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/deployments), it's not available on https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/, hinting a configuration mistake in project settings.

**Comment by paolo-de-rosa** [comment]
Thanks for the feedback, indeed gh-pages are not configured. It has been disabled for now.
