### ISSUE TITLE
How does eIDAS mitigate the risk of bad apples in the UK.

### ISSUE THREAD

**Issue by ryanbnl** [eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework#94]
In the eIDAS regulation:

Member States license a regulator for their country. The regulator licenses and polices the (q)TSPs for their country.

A huge vulnerability here is a bad actor state. For example consider a hypothetical situation: one of the EU Member is quietly compromised by our strategic rivals. Lets call them the Tsardom. This member state, which full controls their regulators, and by extension, all (q)TSPs in their country, provides the security services of the Tsardom full access to their (q)TSP. They use this to issue certificates for several major European banks, which are then used by the Tsar's security service to MITM the sessions of bank users over Europe, sowing chaos and putting the Union in a deep recession.

What mitigations are in place to stop this happening?

**Comment by jinza** [comment]
State control is indirect. 
Supervisory bodies (SB) receive "Conformity Assessment Report" (CAR) from the Trust Service providers afer a Conformity Assessment (Audit) performed by a Conformity Assessment Body. The CAR is delivered to the TSP and then the TSP send this CAR to the SB. After analyzing the CAR and perhaps asking for additional information, the SB decides whether to include the TSP in the TSL (Trusted Services List) or not. Once included in the TSL, the trust services are considered "qualified" and the Trust Service Provider (TSP) becomes a QTSP (Qualified Trust Service Provider). 
There is no possibility for the SB to issue certificates.
